### ISSUE TITLE
Unable to load template file 'tinymce_init.tpl' in 'file:section-edit.html' 

### ISSUE THREAD

**Issue by levagabond** [InformatiqueProg/Section#1]
Bonjour
Impossible d'utiliser ce module, ilme renvoi ce message : Unable to load template file 'tinymce_init.tpl' in 'file:section-edit.html' 
Avez-vous une solution ?? 
A+

**Comment by InformatiqueProg** [comment]
Bonjour,
Thélia 2.1.1 minimum est requis , ainsi que tinymce, c'est bien le cas ?

Cordialement

**Comment by levagabond** [comment]
Bonsoir

Thelia 2.1.3 par contre, je n'ai pas activé tinymce ..

A+

2015-05-25 10:34 GMT+02:00 Christophe notifications@github.com:
